### ISSUE TITLE
The current version is damaged

### ISSUE THREAD

**Issue by dlejay** [trufae/Therm#73] opened 2022-12-14 12:38 UTC
The current release (from GitHub or Homebrew) is declared damaged by macOS Ventura.

**Comment by trufae** [comment] 2022-12-16 15:16
Thanks for the heads up, i will try to find some time to get the dmg built into the CI, i dont want to push builds from my laptop. But as a quick "fix" i just run "make dist" and uploaded a new zip, can you confirm if it works for you now?

https://github.com/trufae/Therm/releases/tag/0.5.0

**Comment by dlejay** [comment] 2022-12-16 23:14
It no longer says that it's damaged, but it “quits unexpectedly”. Impossible to open.

**Comment by trufae** [comment] 2022-12-22 13:07
That's weird.. i did a new build. but still i have decided to rewrite Therm in Swift and on top of SwiftTerm. I will commit that stuff when i get it to work and i plan to stop maintaining this fork, the new Therm will be faster and cleaner and the CI will be able to provide the release files.

Let me know if the new zip works for you :/
[Therm-0.5.0.zip](https://github.com/trufae/Therm/files/10287096/Therm-0.5.0.zip)

**Comment by trufae** [comment] 2023-01-24 12:27
i think its because my developer certificate was expired, i payed again and did anew build check the release page for the new .zip. i should definitbvely find a better way to distribute and sign this app in the ci, but i would prefer to focus on the Swift rewrite :) thanks for reporting

**Comment by dlejay** [comment] 2023-01-24 14:40
When my $HOME is not writeable, Therm quits unexpectedly. When I allow write access, nothing happens after double click.

**Comment by 1dealwaves** [comment] 2023-11-11 11:58
Hi. I'm having the same issues.
First, I couldn't install it via brew. I keep getting the SHA256 mismatch error. 
Second, when I tried to download and install the archive manually, I got the “Therm.app” is damaged and can’t be opened. You should move it to the Trash" error.
I have also tried to add the app to that exceptions list through the Privacy & Security > Developer Tools, and it didn't work.
How do I install the app without that hassling?

**Comment by trufae** [comment] 2023-11-17 08:11
Seems like there are other issues to make Therm build and run on Sonoma, updating the SDK results on the app relying on unexistent frameworks and deprecates apis. im spending some spare time to sort out all those bugs and will publish a new build as soon as possible.

**Comment by 1dealwaves** [comment] 2023-11-17 09:50
> Seems like there are other issues to make Therm build and run on Sonoma, updating the SDK results on the app relying on unexistent frameworks and deprecates apis. im spending some spare time to sort out all those bugs and will publish a new build as soon as possible.

I’d really appreciate your help in this. 
I’m willing to support your intention just as a matter of appreciation. If you have PayPal, buymeacoffee account or smth let me know.

**Comment by trufae** [comment] 2023-11-23 09:37
Thank you, I really appreciate the intentions and interest. But my main blocker right now is spare time, and im picking few minutes everyday to clean code.. but I didnt had a chance to spot the grey screen bug that is probably the only blocker to cut a new release here. I would like to remove a lot of more code and maybe rewrite in Swift eventually.

As an alternative I can suggest you to use Kitty with a custom config I did that mimics the same keybindings and handles splits and tabs and looks very similar to what Therm does. Here's my config file:

gemini://lolcathost.org/tmp/rcfiles/kitty.conf

**Comment by trufae** [comment] 2023-12-04 13:07
i get the grey window issue fixed, still a bunch of deprecation warnings to fix , and fonud tons of code that can be removed too. but at least now it works (but tabs wont be displayed) current issue is that i cant get the titlebar to be transparent, seems like xib + objc code is ignored :<< but its just an aesthetic issue, but the funcionality is good. and if you use it fullscreen thats not noticeable

**Comment by trufae** [comment] 2023-12-04 19:08
Finally found the bugs,p fixed the 0.5 zip and released 0.6 with a bunch of new features and rebuilt for sonoma. I'm closing this because i have confirmed the bug is fixed by asking some friends to download it and try it :)

Can you update the brew formula now? thank you!

**Closed as completed by trufae** 2023-12-04 19:08 UTC
